version: "3.7"
services:
  server_tf1:
    build: 
      context: .
      dockerfile: Dockerfile_tf1
    ports: 
      - "5001:5000"
    volumes:
      - ./:/app
    network_mode: bridge
  server:
    build: .
    ports: 
      - "5000:5000"
    volumes:
      - ./:/app
    network_mode: bridge